### ISSUE TITLE
Disale 3D Touch 

### ISSUE THREAD

**Issue by bombez** [livechat/chat-window-ios#12] opened 2018-01-10 13:56 UTC
Hi,
I would like to know if there is a possibility to disable the 3D Touch functionality.
To be more clear I've attach a video.

Thanks
[issue-24.mov.zip](https://github.com/livechat/chat-window-ios/files/1618942/issue-24.mov.zip)

**Comment by Jercik** [comment] 2018-01-23 14:15
Hi, the issue is fixed in version `2.0.10`. Please update your dependency.

**Closed by Jercik** 2018-01-23 14:15 UTC
