### ISSUE TITLE
Localized string not found

### ISSUE THREAD

**Issue by rupeshmishra90** [livechat/chat-window-ios#68] opened 2020-08-24 10:08 UTC
I've implemented LiveChat in ios. when I'm going to upload an attachment then got options from where we can upload an attachment. There are showing "localized string not found" on camera and gallery options. like following attachment.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-24 at 11 29 12](https://user-images.githubusercontent.com/25951005/91032564-c31c2e00-e61f-11ea-9ed8-5cd87a822701.png)

**Comment by kamil-szostakowski** [comment] 2020-09-15 07:46
Hi @rupeshmishra90 could you please provide more details on how did you integrate the widget? What are the languages supported by your app? On this screen there are two languages mixed together which is odd. I tested that on our end and the widget in an app supporting Spanish (if I'm not mistaken) language looks like this. All the options are properly translated.


<img width="322" alt="screen-spanish" src="https://user-images.githubusercontent.com/9430934/93181053-45d46c80-f738-11ea-97c1-ac302f7a1295.png">

**Comment by rupeshmishra90** [comment] 2020-10-21 04:40
> Hi @rupeshmishra90 could you please provide more details on how did you integrate the widget? What are the languages supported by your app? On this screen there are two languages mixed together which is odd. I tested that on our end and the widget in an app supporting Spanish (if I'm not mistaken) language looks like this. All the options are properly translated.
> 
> <img alt="screen-spanish" width="322" src="https://user-images.githubusercontent.com/9430934/93181053-45d46c80-f738-11ea-97c1-ac302f7a1295.png">

I'm using spanish and english in my application. I' facing issue in case of spanish

**Comment by rupeshmishra90** [comment] 2020-10-21 04:40
Please provide me solution.

**Comment by kamil-szostakowski** [comment] 2021-01-12 09:01
@rupeshmishra90 could you please provide a minimal example reproducing this issue? It works perfectly fine on our end.

**Comment by rupeshmishra90** [comment] 2021-02-24 06:00
Using following reference to use

https://developers.livechat.com/docs/getting-started/installing-livechat/ios-widget/

**Comment by rupeshmishra90** [comment] 2021-02-24 12:04
[Example-Swift.zip](https://github.com/livechat/chat-window-ios/files/6035771/Example-Swift.zip)

**Comment by rupeshmishra90** [comment] 2021-02-24 12:04
check this

**Comment by rupeshmishra90** [comment] 2021-02-24 12:17
I've put strings key value but not reflected

"Browse" = "Vistazo";

**Comment by rupeshmishra90** [comment] 2021-03-01 12:38
Please provide a solution we are struck on it

**Comment by kamil-szostakowski** [comment] 2021-03-11 19:21
@rupeshmishra90 the problem starts with this method `Bundle.swizzleLocalization()` when you will comment out this part the image selection UI starts working as expected. However I feel like this is not your real issue. You just want to see the entire chat widget translated to Spanish, am I correct?

**Comment by rupeshmishra90** [comment] 2021-03-15 12:48
Yes, I want to see the entire chat widget translated to Spanish

**Comment by kamil-szostakowski** [comment] 2021-03-17 17:09
@rupeshmishra90 you can set the widget language in the agent app settings. Please let me know if that solves your problem.

<img width="1226" alt="Zrzut ekranu 2021-03-17 o 18 06 39" src="https://user-images.githubusercontent.com/9430934/111508267-d02f7480-874b-11eb-8a04-57d3a8645c75.png">

**Comment by rupeshmishra90** [comment] 2021-03-30 12:12
Can we set multiple language from here?

**Comment by rupeshmishra90** [comment] 2021-03-30 12:14
I have a doubt if there are two users and one using english language and other using spanish then which language we have to set here.

**Comment by kamil-szostakowski** [comment] 2021-03-31 10:53
@rupeshmishra90 the dynamic language setting is not currently supported in our widget. Please file a separate ticket with a feature request so we will be able to proceed further.

**Comment by kamil-szostakowski** [comment] 2021-04-06 16:49
Closing as clarified.

**Closed by kamil-szostakowski** 2021-04-06 16:49 UTC
Labels: under investigation

**Comment by prabakaranm269** [comment] 2022-01-05 13:59
Hi, I'm facing **localized string not found** issue in chat page
I have used 3 languages in my App
Added strings in localised file like below

```
"Photo Library" = "Photo Library";
"Choose Files" = "Choose Files";
```
```
"Choose Files" = "Photothèque";
"Choose Files"= "Choisir des fichiers";

"Photo Library" = "फोटो लाइब्रेरी";
"Choose Files" = "फ़ाइलें चुनें";
```

PFA, please anyone help me 
Thanks in advance
![Simulator Screen Shot - iPhone 12 - 2022-01-05 at 15 32 49](https://user-images.githubusercontent.com/44673016/148228831-f7abc664-3ca9-4be8-8339-3cf8121bedd7.png)

**Comment by rupeshmishra90** [comment] 2022-01-06 02:13
Hi,


Is this chat support any third party or created by you.

If it's a third party then please ask them to take title from your side.

**Comment by prabakaranm269** [comment] 2022-01-11 11:10
Hi @rupeshmishra90 , Can you please let me know what is the issue there, then how to fix it
For me still this issue is open

**Comment by prabakaranm269** [comment] 2022-01-18 05:00
Hi @kamil-szostakowski I'm facing that localised string not found issue, how to solve this?

**Comment by rupeshmishra90** [comment] 2022-01-18 09:00
You need to ask with livechat team.

They said that you need to create two channels like one for English and
second for other language and redirect accordingly.

**Comment by prabakaranm269** [comment] 2022-01-18 09:27
Okay @rupeshmishra90 
Any options to show English only, is this possible 
I mean if I changed English to French in my App Chat page will show only English

**Comment by rupeshmishra90** [comment] 2022-01-18 09:48
You can change to create Chanel with lagenge French

**Comment by prabakaranm269** [comment] 2022-01-18 10:10
Okay, in Chat admin panel right?

**Comment by rupeshmishra90** [comment] 2022-01-19 14:38
Yes, that's right.

**Comment by prabakaranm269** [comment] 2022-02-01 09:46
I have removed other language strings from my App, added English text alone like below, but still I'm facing same issue
```
// ---- Live Chat Bot -----//
"PHOTO_LIBRARY" = "Photo Library";
"Choose Files" = "Choose Files";
```

**Comment by prabakaranm269** [comment] 2022-02-01 10:11
@rupeshmishra90 I have shared my source code please check below link
https://we.tl/t-keQwcehToc
