### ISSUE TITLE
Swift package manager not supported

### ISSUE THREAD

**Issue by Anubis91** [livechat/chat-window-ios#92] opened 2022-12-05 08:04 UTC
Swift package manager not supported

**Comment by lemonandlime** [comment] 2022-12-09 14:20
...or at least its not working. There is a Package.Swift that looks like it worked sometime in the past but now it does not load into a clean project with only this dependency

**Comment by lemonandlime** [comment] 2024-12-02 16:25
Haven't tried in a long while. If it works for you it's probably fixed

**Comment by kamil-szostakowski** [comment] 2024-12-04 14:52
Closing as not reproducible.

**Closed by kamil-szostakowski** 2024-12-04 14:52 UTC
