### ISSUE TITLE
Problem using LiveChat

### ISSUE THREAD

**Issue by llKoull** [livechat/chat-window-ios#14] opened 2018-01-18 12:25 UTC
Hi!

I'm using this library in my App but i detected some crashes in LiveChat.swift line 117

`NotificationCenter.default.addObserver(forName: NSNotification.Name.UIApplicationDidBecomeActive, object: nil, queue: nil) { (notification) in
            self.window.frame = UIApplication.shared.keyWindow!.frame
        }`

Maybe the problem is that keyWindow is nil and when it tries to access, the app gets crashed. Do you think that delaying the execution of `self.window.frame = UIApplication.shared.keyWindow!.frame` could be a solution?

Thanks and best regards,

**Comment by Jercik** [comment] 2018-01-23 14:11
Hi, I can't reproduce your issue, but certainly if `UIApplication.shared.keyWindow` would be `nil`, app would crash. I've added `if let` statement instead of force unwrapping `UIApplication.shared.keyWindow!`. Please check if issue is fixed in version `2.0.10`.

**Comment by llKoull** [comment] 2018-01-23 15:43
Great! thanks for your help @Jercik ^_^

**Closed** 2019-03-05 16:24 UTC
